config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'ui(/:action)', controller: 'ui'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'register', to: 'users#new', as: :register
  get 'home', to: 'pages#front', as: :home
  root to: 'pages#front'

  resources :users, param: :slug, except: %i[index new destroy]
  resources :settings, param: :slug, only: %i[edit update]
  resources :sessions, only: :create
  resources :businesses, param: :slug, except: :destroy do
    resources :reviews, param: :slug, except: %i[index destroy]
    get 'search', on: :collection
  end
  resources :reviews, only: :index
  resources :tags, param: :slug, only: :show
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :require_user, only: %i[create new edit update]

  def index
    @pagy, @businesses = pagy(Business.all)
  end

  def show
    @business = Business.find_by slug: params[:slug]
    @pagy, @reviews = pagy(@business.reviews)
  end

  def create
    @business = Business.new(business_params.merge!(user: current_user))
    add_tags_to_business if tag_params[:tags]
    if @business.save
      flash[:success] = 'Congratulations! You have added a new business.'
      redirect_to businesses_path
    else
      flash.now[:danger] = 'One or more inputs are invalid, please address the errors.'
      render :new
    end
  end

  def new
    @business = Business.new
  end

  def edit
    @business = Business.find_by slug: params[:slug]
  end

  def update
    @business = Business.find_by slug: params[:slug]
    if @business.update(business_params)
      update_business_tags if tag_params[:tags]
      flash[:success] = 'Changes saved'
      redirect_to business_path(@business)
    else
      flash.now[:danger] = 'One or more inputs are invalid, please address the errors.'
      render :edit
    end
  end

  def search
    @search_name = params[:search_name]&.strip
    @search_location = params[:search_location]&.strip
    @pagy, @businesses = pagy(Business.search(name: @search_name, location: @search_location))
  end

  private

  def business_params
    params.require(:business).permit(:name, :address_1, :address_2, :city, :country, :phone, :price)
  end

  def tag_params
    params.require(:business).permit(tags: [:name])
  end

  def add_tags_to_business
    Business.transaction do
      tag_params[:tags].each do |tag_param|
        if tag_param[:name].present?
          tag = create_new_tag_or_find_by tag_param
          @business.tags << tag unless business_already_has tag
        end
      end
    end
  end

  def update_business_tags
    @business.tags.clear
    add_tags_to_business
  end

  def business_already_has(tag)
    @business.tags.map(&:name).include?(tag.name)
  end

  def create_new_tag_or_find_by(tag_param)
    Tag.find_by(name: tag_param[:name].titleize) || Tag.create(tag_param)
  end
end

app/views/businesses/_business_card.html.haml
%li
  .card.mt-5
    .card-body
      .row
        .col-sm-8
          %h4.card-title
            = "#{index + 1}."
            %span.mr-3
              = link_to business.name, business_path(business)
            = render 'shared/write_a_review_button', business: business
          = render 'review_info', business: business
          %h6.card-subtitle.text-muted.mb-3
            = render 'price_and_tag_info', business: business
        .col-sm-4
          %address.float-sm-right.mr-4
            %ul
              %li 
                = business.phone
              %li 
                = business.address_1
              %li 
                = business.city
      .row
        %p.px-3
          = business.first_review_summary
          - if business.first_review_summary
            %span
              = link_to "Read More", business_path(business) 

app/views/businesses/_business_card_list.html.haml
%ul
  - businesses.each_with_index do |business, index|
    = render 'business_card', business: business, index: index + @pagy.offset

= render 'shared/pagy', pagy: @pagy

app/views/businesses/_form.html.haml
= bootstrap_form_for @business do |f|
  = f.text_field :name, class: "form-control-sm"
  = f.text_field :address_1, class: "form-control-sm"
  = f.text_field :address_2, class: "form-control-sm"
  = f.text_field :city, class: "form-control-sm"
  = f.text_field :country, class: "form-control-sm"
  = f.phone_field :phone, class: "form-control-sm"
  = f.select :price, [5, 4, 3, 2, 1].map { |p| [print_euros(p), p] }, { include_blank: true }
  = f.label :name, 'Tags <small class="text-muted ml-2">Enter up to three tags</small>'.html_safe
  %div.form-row.mb-2
    - ["Food", "Irish", "Cheap"].each_with_index do |placeholder, index|
      %div.col
        = text_field_tag "[business]tags[]name", @business.tags[index]&.name, hide_label: true, placeholder: "e.g. #{placeholder}", class: "form-control form-control-sm mb-2" 
  = f.submit "Submit", class: "btn btn-danger mr-2"
  = link_to 'Cancel', businesses_path

app/views/businesses/_price_and_tag_info.html.haml
-if business.price
  = display_price(business.price)
  - unless business.tags.blank? 
    &#8226;
%span
  %ul.d-inline-block
    - business.tags.each do |tag|
      %li.d-inline-block
        = link_to tag.name, tag_path(tag)
        - unless business.tags.last == tag
          &#8226;

app/views/businesses/_review_info.html.haml
.mb-2
  = render 'reviews/star_details', rating: business.rating
  %span.text-muted.ml-2 
    = pluralize(business.reviews.count, 'review')

app/views/businesses/edit.html.haml
.container
  .row.mt-5
    .col-md-8
      = render 'shared/title', title:  "Edit #{@business.name}"
      = render 'form'

app/views/businesses/index.html.haml
.container
  .row.mt-5
    .col
      = link_to "+ Add New Business", new_business_path, class: "btn btn-outline-danger"
    .col.text-right.text-muted
      = render 'shared/showing', pagy: @pagy
  .row
    .col
      = render 'business_card_list', businesses: @businesses

        

app/views/businesses/new.html.haml
.container
  .row.mt-5
    .col-md-8
      = render 'shared/title', title: "Add New Business"
      = render 'form'

app/views/businesses/search.html.haml
.container
  .row.mt-5
    .col
      - if @businesses.empty?
        %h4.font-weight-bold
          = "Sorry, no results found for" 
          %span.text-danger
            = "#{@search_name}"
          %span.text-primary
            = "#{@search_location}"
      - else
        %h4.font-weight-bold
          %span
            = "Search results for" 
          %span.text-danger
            = "#{@search_name}"
          %span.text-primary
            = "#{@search_location}"
    .col.text-right.text-muted
      = render 'shared/showing', pagy: @pagy
  .row
    .col
      = render 'business_card_list', businesses: @businesses, pagy: @pagy
        

app/views/businesses/show.html.haml
.container
  .row.mt-5
    .col
      .row
        .col-sm-8
          %h1
            = @business.name
          .mb-2
            = render 'review_info', business: @business
          %h6.text-muted.mb-3
            = render 'price_and_tag_info', business: @business
            - if logged_in?
              = link_to edit_business_path(@business), class: 'd-block' do
                %i.fas.fa-pen.mr-2
                Edit this business
        .col-sm-4
          = render 'shared/write_a_review_button', business: @business
      .row
        .col
          %address
            %ul
              %li.mb-2
                %i.fas.fa-phone.text-muted.mr-2
                = @business.phone
              %li
                %i.fas.fa-map-marker-alt.text-muted.mr-2
                = @business.address_1
              %li.pl-4
                = @business.city
      %hr
      .row
        .col
          %h5.my-4
            %span.text-danger.font-weight-bold Reviews
            = "for #{@business.name}"
      .row
        .col
          %ul
            - @business.reviews.each do |review|
              = render 'reviews/review_card', review: review, rating: review.rating, display_card_header: false
  .row
    .col
      = render 'shared/pagy', pagy: @pagy