config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'ui(/:action)', controller: 'ui'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'register', to: 'users#new', as: :register
  get 'home', to: 'pages#front', as: :home
  root to: 'pages#front'

  resources :users, param: :slug, except: %i[index new destroy]
  resources :settings, param: :slug, only: %i[edit update]
  resources :sessions, only: :create
  resources :businesses, param: :slug, except: :destroy do
    resources :reviews, param: :slug, except: %i[index destroy]
    get 'search', on: :collection
  end
  resources :reviews, only: :index
  resources :tags, param: :slug, only: :show
end

app/views/shared/_footer.html.haml
.container
  .row.d-flex.justify-content-center
    .col-sm-4
      %img.img-fluid(src="/images/city-1117433_1280.png")
        %p.text-center.mt-2
          Copyright &copy; <span id="year"></span> Yep 
          %span

%script
  $('#year').text(new Date().getFullYear());

app/views/shared/_header.html.haml
%section#top-header.bg-danger.py-2
  .container
    .row.align-items-center
      .col-md-2
        %h1.text-center
          = link_to "Yep", home_path, class: 'text-white yep'
      .col-md-7
        = render 'shared/search_bar', search_name: search_name, search_location: search_location
      - if logged_in?
        .col-md-3
          .d-flex.justify-content-around
            = link_to businesses_path, class: "btn bg-custom-red px-3 my-2 bg-danger text-white", "data-toggle" => "tooltip", "data-placement" => "bottom", title: "See All Businesses" do
              %i.far.fa-building
            = link_to reviews_path, class:"btn bg-custom-red px-3 my-2 bg-danger text-white", "data-toggle" => "tooltip", "data-placement" => "bottom", title: "See All Reviews" do
              %i.far.fa-star
            .dropdown
              .btn.btn-group(data-toggle="dropdown")
                %button.btn.btn-light.no-blue-glow.user-icon(type="button")
                  %i.far.fa-user
                %button.btn.text-white.bg-custom-red.dropdown-toggle.no-blue-glow.px-2(type="button")
              .dropdown-menu
                .d-flex
                  = link_to user_path(current_user), class: "user-icon bg-light d-block p-2 ml-2 rounded align-self-center" do
                    %i.far.fa-user.fa-3x
                  .p-2.mr-2
                    = render 'users/profile', user: current_user
                .dropdown-divider
                = link_to user_path(current_user), class: "dropdown-item text-primary" do
                  %i.far.fa-user.text-secondary.mr-2.fixed-width-1.text-center
                  %span.small.font-weight-bold
                    About Me
                = link_to edit_setting_path(current_user), class: "dropdown-item text-primary" do
                  %i.fas.fa-cog.text-secondary.mr-2.fixed-width-1.text-center 
                  %span.small.font-weight-bold
                    Account Settings
                .dropdown-divider
                = link_to "Log Out", logout_path, class: "dropdown-item text-primary"
      - else
        .col-md-3
          .d-flex
            = link_to 'Log in', login_path, class: "btn btn-danger bg-custom-red text-white"
            = link_to 'Sign Up', register_path, class: "btn btn-light ml-3"



          

%script
  $('[data-toggle="tooltip"]').tooltip();

        

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}", class: "ml-5" if msg.is_a?(String)

app/views/shared/_pagy.html.haml
- if pagy.count > pagy.items
  = pagy_bootstrap_nav(pagy).html_safe

app/views/shared/_search_bar.html.haml
= form_tag search_businesses_path, method: "get", class: "input-group" do
  .input-group-append
    .input-group-text.white-background.no-border.font-weight-bold.rounded-left Find
  %input.form-control.no-blue-glow.no-border-left(type="text" name="search_name" value="#{search_name}" placeholder="e.g. Bunsen")
  .input-group-append
    .input-group-text.white-background.no-border.font-weight-bold Near
  %input.form-control.no-blue-glow.no-border-left(type="text" name="search_location" value="#{search_location}" placeholder="e.g. Dublin")
  = button_tag '', class: "input-group-append text-white bg-custom-red px-4 rounded-right no-blue-glow d-flex flex-column" do
    %i.fa.fa-search.align-self-center.mt-2

app/views/shared/_showing.html.haml
= "Showing #{pagy.from} to #{pagy.to} of #{pagy.count}"   

app/views/shared/_title.html.haml
%h4.text-danger.font-weight-bold.mb-4 
  = title

app/views/shared/_write_a_review_button.html.haml
= link_to new_business_review_path(business), class: "btn btn-danger" do
  %i.fas.fa-star.mr-2 
  Write A Review