config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'ui(/:action)', controller: 'ui'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'register', to: 'users#new', as: :register
  get 'home', to: 'pages#front', as: :home
  root to: 'pages#front'

  resources :users, param: :slug, except: %i[index new destroy]
  resources :settings, param: :slug, only: %i[edit update]
  resources :sessions, only: :create
  resources :businesses, param: :slug, except: :destroy do
    resources :reviews, param: :slug, except: %i[index destroy]
    get 'search', on: :collection
  end
  resources :reviews, only: :index
  resources :tags, param: :slug, only: :show
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user, only: %i[create new edit update]

  def index
    @pagy, @reviews = pagy(Review.all)
  end

  def new
    @review = Review.new
    @review.business = Business.find_by slug: params[:business_slug]
  end

  def edit
    @review = Review.find_by slug: params[:slug]
    if !current_user?(@review.user)
      access_denied(reviews_path)
    else
      render :edit
    end
  end

  def show
    @review = Review.find_by slug: params[:slug]
  end

  def create
    @review = Review.new(review_params.merge(user: current_user))
    @review.business = Business.find_by slug: params[:business_slug]
    save_review
  end

  def update
    @review = Review.find_by slug: params[:slug]
    if !current_user?(@review.user)
      access_denied(reviews_path)
    else
      update_review
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body, :business_slug)
  end

  def update_review
    if @review.update(review_params)
      flash[:success] = 'Review has been updated.'
      redirect_to business_path(@review.business)
    else
      flash[:danger] = 'There was a problem with your inputs'
      render :edit
    end
  end

  def save_review
    if @review.save
      flash[:success] = 'Congratulations, you have added a new review!'
      redirect_to business_path(params[:business_slug])
    else
      flash.now[:danger] = 'There was an error with your inputs'
      render :new
    end
  end
end

app/views/reviews/_form.html.haml
= bootstrap_form_for([review.business, review])  do |f|
  = f.select :rating, [5, 4, 3, 2, 1].map { |r| [print_stars(r), r]}, {}, class: "text-danger"
  = f.text_area :body, rows: 10, label: "Review", placeholder: "Your review helps others learn about great local businesses.                                                                           Please don't review this business if you received a freebie for writing this review, or if you're connected in any way to the owner or employees."
  = f.submit class: "btn btn-danger"

app/views/reviews/_review_card.html.haml
%li.mb-4
  .card
    - if display_card_header
      .card-header
        %span.font-weight-bold Review for 
        = link_to review.business.name, business_path(review.business)
    .card-body
      .row
        .col-sm-4.mb-3
          .row
            .col-md-4
              %i.far.fa-user.fa-3x.text-secondary.bg-light.p-1.mb-3
            .col-md-8
              = render 'users/profile', user: review.user
        .col-sm-8
          .card-title
            .mb-2
              = render 'reviews/star_details', rating: rating
              %span.ml-2.text-secondary 
                = review.created_at.strftime("%d/%m/%Y")
              - if review.user == current_user
                = link_to edit_business_review_path(review.business, review), class: 'd-block' do
                  %i.fas.fa-pen.mr-2
                  Edit
          .card-text
            = simple_format(review.body)

app/views/reviews/_star_details.html.haml
- full_stars(rating).times do
  %i.fas.fa-star.text-danger
- if half_star?(rating)
  %i.fas.fa-star-half-alt.text-danger

app/views/reviews/edit.html.haml
.container
  .row.mt-5
    .col-lg-8
      %h4.text-secondary.font-weight-bold.mb-4 
        %small.mr-1
          Edit review for
        = link_to(@review.business.name, business_path(@review.business))
  .row
    .col-lg-8
      = render 'form', review: @review
        

app/views/reviews/index.html.haml
.container
  .row.my-5
    .col
      = link_to "+ Add New Review", businesses_path, class: "btn btn-outline-danger"
    .col.text-right.text-muted
      = render 'shared/showing', pagy: @pagy
  .row
    .col
      %ul
        - @reviews.each do |review|
          = render 'review_card', review: review, rating: review.rating, display_card_header: true  
  .row
    .col
      = render 'shared/pagy', pagy: @pagy
      

app/views/reviews/new.html.haml
.container
  .row.mt-5
    .col-lg-8
      %h4.text-secondary.font-weight-bold.mb-4 
        %small.mr-1
          Write a review for
        = link_to(@review.business.name, business_path(@review.business))
  .row
    .col-lg-8
      = render 'form', review: @review
        